name: Scala Maven Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          mvn-version: '3.8.1'

      - name: Build and Package with Maven
        run: mvn clean package

      - name: Run Unit Tests and Code Coverage
        run: mvn test

      - name: Upload JAR to Azure Storage
        uses: azure/storage-blob-upload-action@v1
        with:
          connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          container-name: xmscaled-files'
          source: 'target/artifact.jar'
          destination: 'xmscaled-files/artifact.jar'
