name: Azure Storage Account Deployment (Scala with Maven)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Unzip Scala project if necessary
      - name: Unzip Scala Project
        run: |
          mkdir extracted-scala
          unzip ./scala.zip -d extracted-scala

      # Cache Maven dependencies to speed up build
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Purge local repository cache (optional but helps resolve plugin issues)
      - name: Purge local repository
        run: mvn dependency:purge-local-repository

      # Build with Maven (Clean and Install with Debug)
      - name: Build with Maven
        run: mvn clean install -X

      # Run tests with coverage (JaCoCo and Scoverage)
      - name: Run tests with coverage
        run: mvn test jacoco:report scoverage:report

      # Upload coverage to Codecov (optional)
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      # Log in to Azure (make sure to set AZURE_CREDENTIALS in Secrets)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Upload to Azure Storage Account (adjust for your setup)
      - name: Upload to Azure Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name sitecorescaled \
              --auth-mode key \
              -d xmscaled-files \
              -s target/
