name: Azure Synapse Deployment (Scala with Maven)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17 (or your preferred JDK)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Maven
        uses: actions/setup-maven@v3  # Add Maven setup
        with:
          maven-version: '3.8.1' # Or your preferred Maven version

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package

      - name: Run tests with coverage (ScalaTest example)
        run: mvn scoverage:report

      - name: Upload coverage to Codecov (Optional)
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Synapse
        uses: azure/synapse-workspace-deploy@v1 # Or Azure CLI commands
        with:
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource-group: TCCC-rg
          workspace-name: coke-ws
          artifact-path: target/*.jar # Path to your JAR
